### ISSUE TITLE
A importância da UX no sucesso do seu app

### ISSUE THREAD

**Issue by angelobelchior** [MonkeyNights/podcast#2]
Caminho das pedras para criar uma boa experiência de usuário.

**Comment by arthurkarrer** [comment]
Acho que essa é a maior dificuldade de todo programador, fazer algo agradável e bonito

**Comment by heytherewill** [comment]
[Publicado!](http://mkncast.azurewebsites.net/2017/09/27/a-importancia-da-ux-no-sucesso-do-seu-app/)
