### ISSUE TITLE
Migrando um projeto xamarin para Net Standard 

### ISSUE THREAD

**Issue by marcodemagalhaes** [MonkeyNights/podcast#9]
Gostaria de saber quais são os benefícios de se migrar um projeto Xamarin para .net standard e sobre as dificuldades que vocês tiveram quando foram migrar algum projeto para .net Standard.

E se possível o caminho das pedras para fazer isso sem perder noites de sono ou ter uma overdose de café.

**Comment by heytherewill** [comment]
Duplicado do #6. Adiciona a sua proposta como um comentário naquele issue e dê um upvote no post original para mostrar seu interesse no tema :)
